[package]
name = "bevy_tiny_data_flow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11" }
tiny_utils_proc_macros = { path = "macros" }
